### ISSUE TITLE
Can't control playback

### ISSUE THREAD

**Issue by teccheck** [ceuk/spotui#10]
I set spotui up like the readme shows. It shows what song is playing and I can browse through my playlists etc. But I can't control the playback.

My Setup:
* Ubuntu 19.10
* Spotify Free (maybe that's the problem)
* Web player as "demon"
* Default Gnome Terminal

**Comment by ceuk** [comment]
I've not used Spotify free in ages but am I right that you can't play specific tracks etc on the actual client even? If that's the case this is almost certainly because you're on free I'm afraid :(

**Comment by teccheck** [comment]
With the web client on pc I don't have any restrictions other than not being able to download songs.
I can select any song I want to play and I can enable and disable shuffle. So this should not be a problem.
I think the problem is that you cant connect to 3rd party clients with the free version
