### ISSUE TITLE
Localhost refused to connect

### ISSUE THREAD

**Issue by Proladon** [ceuk/spotui#15]
**To Reproduce**
1. spotui
2. redirect... (http://localhost:8888/Proladon, setting both .spotuirc and soptify dashboard)
(and also tried 127.0.0.1)
3. showing authorization
4. Click agree
5. localhost refused to connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/35193493/95950153-a84b8600-0e26-11eb-8641-a1471d88bf22.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Btw, Windows should install `windows-curses`
or it will show `no module named '_curses'`

**Comment by ceuk** [comment]
Hey, this is actually how it's supposed to work. You just need to copy the URL of that page and paste it back into the terminal. 

I'll have a look at the windows curses thing, thanks for raising :)

**Comment by Proladon** [comment]
Oh, omg lol, forgive me dumb question :(

**Comment by ceuk** [comment]
No probs, it's not a very intuitive process - blame the spotipy library :)
