### ISSUE TITLE
My play button is changing to Chinese character

### ISSUE THREAD

**Issue by fachrizalrz** [ceuk/spotui#19]
**Describe the bug**
My play button is changing to Chinese character, and the progress bar is not working

契咽 Afterglow - Ed Sheeran                                       02:22/03:05
                                                                                 ██████████████████████████████████████████████████████████                 

**Comment by ceuk** [comment]
see #9 

Add `use_nerd_fonts = no` under the `[other]` section in `~/.config/spotui/.spotuirc`

It should look something  like this:

![image](https://user-images.githubusercontent.com/1681236/73738273-1a1dec80-473c-11ea-9893-1fe6fc271a12.png)
