### ISSUE TITLE
[Question] Alternative for Free Non-Premium accounts

### ISSUE THREAD

**Issue by omnigenous** [ceuk/spotui#39]
Since SpoTUI doesn't support it, is there good alternative?

**Comment by ceuk** [comment]
Hey @omnigenous it's not really that SpoTUI doesn't support it, it's that the Spotify API doesn't support/allow it. I'm not aware of any workarounds off the top of my head, and I imagine anything you did try and do might potentially break the Spotify terms of service so I'd be careful

**Comment by BrownNPC** [comment]
@omnigenous I made a [fork of this project](https://github.com/BrownNPC/Youtube-Music-TUI)
It allows you to play youtube music playlists, for free.
You just need to convert your Spotify playlists using either [this](https://soundiiz.com/tutorial/spotify-to-youtube-music) website or [this](https://github.com/linsomniac/spotify_to_ytmusic) script
