### ISSUE TITLE
start_playback has it's context_uri and track_uri parameters reversed

### ISSUE THREAD

**Issue by RubenBrocke** [ceuk/spotui#4]
**Describe the bug**
start_playback has it's context_uri and track_uri parameters reversed
they are now
```python
def start_playback(self,
                       device_id,
                       track_uri=None,
                       context_uri=None,
                       offset=None):
```

but they should be

```python
def start_playback(self,
                       device_id,
                       context_uri=None,
                       track_uri=None,
                       offset=None):
```

**Comment by ceuk** [comment]
I actually switched it on purpose for some reason :grin: just seemed to make more sense that way around. Will consider refactoring if this project ever gets any additional contributors who find it confusing that the signature differs from its eponymous Spotipy counterpart.

**Comment by RubenBrocke** [comment]
Well the problem is that they are used in the wrong order for the spotipy call too..

**Comment by ceuk** [comment]
Looks correct to me? [here's](https://github.com/ceuk/spotui/blob/master/spotui/src/spotifyApi.py#L63) where I make the call to Spotify with the [start_playback](https://spotipy.readthedocs.io/en/2.6.1/?highlight=start_playback#spotipy.client.Spotify.start_playback) Spotipy method. As you can see I swap  context and track around unless I'm missing something else

**Comment by RubenBrocke** [comment]
Oh i see it was my confusion with the difference between spotipy and your api.
