### ISSUE TITLE
No matching distribution found for spotui

### ISSUE THREAD

**Issue by nojohnso** [ceuk/spotui#6]
Currently using latest version of Linux Mint.

**Comment by ceuk** [comment]
Are you using Python 2 or 3? (Spotui requires v3). Try `pip3 install spotui` maybe if you haven't already?

**Comment by nojohnso** [comment]
That worked but now I receive this error:
`error: invalid command 'bdist_wheel'`

**Comment by nojohnso** [comment]
Nevermind! I just had to do a pip install of wheel.
