### ISSUE TITLE
Cannot play tracks on Chromebook.

### ISSUE THREAD

**Issue by extremepayne** [ceuk/spotui#8]
**Describe the bug**
Okay, I have no idea what I'm getting wrong, but I can't play any tracks. This might have to do with my system since it's ChromeOS, but I really don't know. Linux is supposed to be able to interface with the sound.
Works: fetching playlists, songs, top tracks, etc. Search. All keybindings, etc.
Doesn't work: Showing/selecting devices (I have both the official PWA and spotifyd running), detecting if another client is playing a song (always says "nothing is playing", despite songs playing on web client or phone), and playing songs. The bind to start a track is <kbd>Enter</kbd>, right?

**To Reproduce**
I followed the instructions in the README with exactness. Like I said before, this could just be my system.

**Expected behavior**
Being able to play tracks.

**Screenshots**
![image](https://user-images.githubusercontent.com/46696318/72657314-f860ef00-395f-11ea-9531-81ff03b46487.png)
I had a song playing then, via the PWA.
![image](https://user-images.githubusercontent.com/46696318/72657433-69ed6d00-3961-11ea-9471-c7b29aa36af4.png)
Yes, I did have spotifyd running right then. I used `ps -aux` to check.

**Desktop (please complete the following information):**
 - OS: ChromeOS 79 with Debian 9 (Stretch) VM/container (built-in "Linux (beta)" feature)
 - Browser Chrome 79

Chromebook C330

**Additional context**
Does spotifyd require configuration?
If this is just a problem with my system, could someone maybe reproduce and try to figure it out? I understand if you don't have a Chromebook, but this is just frustrating.

**Comment by ceuk** [comment]
Hey @extremepayne, to rule out any issues with Spotifyd could you try playing a song in something that **does** work (e.g. an official client) and then starting up spotui to see if you can see anything playing? 

(Also, re: debugging spotofyd, try run with the `--no-daemon` command to see if it's erroring)

**Comment by extremepayne** [comment]
Okay, so thanks to your suggestion, it appears that `spotifyd` isn't the problem. I think. 
```
$ spotifyd --no-daemon
No config file specified. Running with default values
No proxy specified
Using software volume controller.
```
![image](https://user-images.githubusercontent.com/46696318/72673181-11cb6f00-3a24-11ea-9c67-9aedab8d0f8a.png)

I have before tried playing a song via a different method (i.e. the PWA/website, the only option on my Chromebook) and it doesn't show up on spotui.
![image](https://user-images.githubusercontent.com/46696318/72673209-67a01700-3a24-11ea-87cf-b4f06f4e201b.png)

I would try using a different TUI to make sure this is even possible from within the VM/container, but Rigellute's version wouldn't compile.

Anddd... I don't know. I am honestly lost.
¯\\\_(ツ)\_/¯

Thanks for the prompt response!

**Comment by ceuk** [comment]
The only thing I can think is that your authentication isn't working or you can't connect to the Spotify API for some other reason.

You can rule out the latter by just pinging api.spotify.com

If that isn't the issue you can delete your cached credentials and try re-authenticate by removing the file at `~/.cache-(your spotify username)`

**Comment by ceuk** [comment]
The cache file might not actually be in your home directory. I'm not 100% sure where spotipy (the library I use to handle auth) creates it. Mine is in my home dir.

**Comment by ceuk** [comment]
Okay, also, try just waiting for 5-10 seconds, It might just appear. There was a slight delay when I tried it earlier
