### ISSUE TITLE
Play, repeat and shuffle come up as Chinese/Japanese characters

### ISSUE THREAD

**Issue by adam-savard** [ceuk/spotui#9]
I don't know if this is because of the shell I'm using or not. My default shell is FISH. I suspect this is due to differences in how Unicode is handled. After submitting this, I'll check if Bash has the same error.

(PS - this is rad and I love it)

OS: Manjaro Linux
Kernel: 5.4.13-3-MANJARO
Shell: fish 3.0.2 
Terminal: cool-retro-term (also happens in Konsole)

EDIT: Also happens in Bash. Not shell dependent, and not terminal dependent

**Comment by adam-savard** [comment]
![Example of what I mean](https://user-images.githubusercontent.com/49501626/73139124-1bb32a80-4041-11ea-9ff9-2f8bdadb3323.png)

Here's an example I forgot to link

**Comment by ceuk** [comment]
I was waiting for this one :) the symbols don't work if you aren't using a patched [nerd font](https://www.nerdfonts.com/). I'll add a config option that allows you to display letters instead of symbols. Should have time over the next few days

**Comment by adam-savard** [comment]
I can never keep up with the amount of stuff available to PC users haha. No idea this existed, but that's cool! And thanks for the heads up!

**Comment by ceuk** [comment]
@adam-savard  this is fixed in 0.1.10, you just need to update and then add `use_nerd_fonts = no` under the `[other]` section in `~/.config/spotui/.spotuirc`

It should look something  like this:

![image](https://user-images.githubusercontent.com/1681236/73738273-1a1dec80-473c-11ea-9893-1fe6fc271a12.png)

**Comment by adam-savard** [comment]
That's awesome, thanks! I will be testing that when I get a few minutes :)
